Numpy Crash Course

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating Arrays

In [11]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [17]:
arr = np.array(my_list)

In [19]:
arr

array([0, 1, 2, 3, 4, 5])

In [21]:
type(arr)

numpy.ndarray

In [23]:
type(my_list)

list

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(3.0)

array([0., 1., 2.])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [37]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [39]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [41]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [43]:
np.arange(30,20)  # 1st arguments should be always be less than 2nd arguments

array([], dtype=int32)

In [45]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [47]:
np.arange()

TypeError: arange() requires stop to be specified.

In [49]:
np.arange(10, 30, 5) # 10 - starting point and 30 - end point , 5 - step count

array([10, 15, 20, 25])

In [51]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [53]:
np.arange(10, 30, 5,8)

TypeError: Cannot interpret '8' as a data type

In [55]:
np.zeros(3)  # parameter tunning (returns a new array filled with zeros with float value)

array([0., 0., 0.])

In [57]:
np.zeros(5, dtype=int) # hyperparameter

array([0, 0, 0, 0, 0])

In [59]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [61]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [63]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [65]:
print('###')
print(type(zero))

###
<class 'numpy.ndarray'>


In [67]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [71]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros([10, 30],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [77]:
np.zeros([5,10]) # by default 1st arguments -- row & 2nd arguments -- columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
n = (6,7)
n1 = (6,8) 
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [83]:
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [85]:
n

(6, 7)

In [87]:
n1

(6, 8)

In [89]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [91]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [97]:
n

(6, 7)

In [99]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [101]:
np.ones((5,4),dtype=int)  # by default 5 - rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [103]:
np.twos([2,3])

AttributeError: module 'numpy' has no attribute 'twos'

In [105]:
np.ones(2)

array([1., 1.])

In [107]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
np.ones([6,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [111]:
range(5)

range(0, 5)

In [113]:
r = range(5)
r

range(0, 5)

In [115]:
for i in r:
    print(i)

0
1
2
3
4


In [117]:
list(range(1,10,3))

[1, 4, 7]

In [121]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [127]:
np.random.rand(5)

array([0.13716425, 0.48225939, 0.0541034 , 0.4457035 , 0.92621117])

In [129]:
np.random.rand(2,4)

array([[0.98070157, 0.78514521, 0.34951448, 0.28199458],
       [0.63980989, 0.04625677, 0.62191519, 0.7754663 ]])

In [131]:
np.random.randint(2,4)

3

In [133]:
np.random.randint(2,20) # 2nd argument is exclusive

4

In [135]:
np.random.randint(0,1)

0

In [137]:
np.random.randint(0,1)

0

In [139]:
np.random.randint(10,20,5)

array([18, 13, 17, 10, 18])

In [141]:
np.random.randint(1,6,4)

array([1, 1, 1, 5])

In [143]:
np.random.rand(3)

array([0.62257697, 0.98063712, 0.00896067])

In [145]:
np.random.randint(1)

0

In [147]:
np.random.randint(30,20,10)

ValueError: low >= high

In [149]:
np.random.randint(-30,20,10)

array([-17,  10, -30, -20, -19,   6,   8,  -7,  -2,   6])

In [151]:
np.random.randint(20,30,10)

array([21, 22, 22, 23, 26, 29, 26, 23, 28, 28])

In [153]:
np.random.randint(5,9) # GET THE VALUE <=1 & >=5

8

In [155]:
np.random.randint(1,12,10)

array([ 3,  5,  2,  1, 11,  7, 11, 11,  3,  5])

In [157]:
np.random.randint(10,40,[10,10]) # generate the element 10-40,with 10*10 matrix

array([[29, 23, 23, 21, 28, 24, 17, 35, 11, 36],
       [26, 30, 22, 39, 14, 13, 30, 10, 17, 15],
       [35, 36, 32, 36, 25, 23, 33, 25, 11, 36],
       [39, 20, 28, 24, 26, 36, 25, 10, 29, 36],
       [33, 30, 14, 29, 29, 28, 32, 17, 27, 39],
       [25, 32, 15, 31, 39, 32, 17, 31, 17, 19],
       [29, 14, 31, 14, 12, 35, 34, 34, 28, 16],
       [24, 37, 30, 34, 32, 33, 22, 18, 27, 34],
       [38, 27, 19, 25, 12, 11, 11, 36, 27, 11],
       [22, 16, 35, 24, 28, 31, 15, 39, 35, 28]])

In [159]:
np.random.randint(1,100,[12,12]) 

array([[65, 44,  8, 47, 79, 14, 82, 81, 61, 99, 15,  2],
       [60, 39, 47, 57, 18, 34, 91, 43, 69, 12, 70, 28],
       [88, 60, 10, 26, 53, 64, 43, 39,  8, 71, 81, 27],
       [37, 76, 80, 47, 12, 59, 32, 51, 24, 82,  6, 51],
       [41, 50, 12, 58, 44, 99, 51, 11, 34, 35, 99, 14],
       [70, 78, 27, 99, 56,  2, 92, 17, 30, 51, 20, 66],
       [ 8, 12, 10, 32, 88, 89, 72, 96, 52, 37, 40, 98],
       [41, 83, 59, 23, 41, 61, 22, 33, 21, 39, 43, 95],
       [62,  7,  3,  3,  9, 29, 22, 26,  1, 17, 78, 78],
       [54, 89, 59, 20, 25,  8, 95, 75, 58, 22,  1, 37],
       [16, 51, 57, 53,  3, 42, 42, 54, 89, 46, 57, 66],
       [94,  8, 67, 25,  3, 22, 87, 38, 90, 76, 80, 46]])

In [161]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [165]:
b = np.random.randint(10,20,[5,4])
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [167]:
type(b)

numpy.ndarray

In [169]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [171]:
b[:]

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [173]:
b[1:3]

array([[18, 14, 17, 13],
       [13, 17, 12, 10]])

In [175]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [177]:
b[1,2]

17

In [179]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [181]:
b[1,3]

13

In [183]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [185]:
b[1,-1]

13

In [187]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [189]:
b[2:3]

array([[13, 17, 12, 10]])

In [191]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [193]:
b[0:-2]

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10]])

In [195]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [197]:
b[0,2]

16

In [199]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [203]:
b[-5,-3]

17

In [205]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [207]:
b[-4,2]

17

In [209]:
np.random.randint(10,20,[4,4])

array([[19, 12, 19, 15],
       [10, 16, 19, 15],
       [10, 11, 13, 10],
       [19, 12, 11, 11]])

In [211]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [213]:
b[-4,-2]

17

In [215]:
b

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

In [217]:
b[-4:2]

array([[18, 14, 17, 13]])

In [219]:
b[:]

array([[13, 17, 16, 11],
       [18, 14, 17, 13],
       [13, 17, 12, 10],
       [14, 10, 12, 19],
       [11, 16, 19, 11]])

Operations

In [222]:
a = np.random.randint(10,20,10)
a

array([16, 19, 11, 11, 18, 12, 10, 15, 19, 16])

In [224]:
id(a)

2444822470288

In [226]:
arr

array([0, 1, 2, 3, 4, 5])

In [228]:
arr2 = np.random.randint(0,100,[10,10])
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [230]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [232]:
arr[:4]

array([0, 1, 2, 3])

In [234]:
arr2[:]

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [236]:
arr2[0:5]

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39]])

In [238]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [240]:
arr2[1,4]

82

In [242]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [244]:
arr2[-5,5]

53

In [246]:
arr2[-5,-5]

53

In [248]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [250]:
arr2[-1,-2]

73

In [252]:
arr2[::-1]

array([[21, 92, 60, 71, 46, 74, 67, 20, 73, 91],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [65, 21, 53, 93, 73, 58, 94, 73, 70, 60]])

In [254]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [256]:
arr2[::-2]

array([[21, 92, 60, 71, 46, 74, 67, 20, 73, 91],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60]])

In [258]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [260]:
arr2[::-3]

array([[21, 92, 60, 71, 46, 74, 67, 20, 73, 91],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [65, 21, 53, 93, 73, 58, 94, 73, 70, 60]])

In [262]:
arr2

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21],
       [68, 59, 59, 11, 10, 72, 22, 53,  0, 97],
       [99, 64, 28, 24, 62, 13, 68, 41, 56, 14],
       [21, 92, 60, 71, 46, 74, 67, 20, 73, 91]])

In [264]:
arr2[:-3]

array([[65, 21, 53, 93, 73, 58, 94, 73, 70, 60],
       [65, 43, 67, 10, 82, 74, 12, 12, 20, 60],
       [31, 61, 60, 14, 31, 86, 61, 81, 59, 13],
       [49, 86, 32, 82, 77, 95, 78, 81, 63,  6],
       [80, 44, 46, 17, 82, 35, 32, 58, 14, 39],
       [70, 29, 17, 39, 81, 53, 41, 98,  0, 10],
       [69,  9,  1, 36, 95, 27, 96,  5, 89, 21]])

In [266]:
arr

array([0, 1, 2, 3, 4, 5])

In [268]:
arr.max()

5

In [270]:
arr.min()

0

In [272]:
arr

array([0, 1, 2, 3, 4, 5])

In [274]:
arr.mean()

2.5

In [276]:
arr

array([0, 1, 2, 3, 4, 5])

In [278]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [280]:
from numpy import *
a = array ([1,2,3,4,9])
median(a)

3.0

without work on import* can you please find the median,mode

In [283]:
arr

array([0, 1, 2, 3, 4, 5])

In [285]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [287]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [289]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [291]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [293]:
arr.reshape(2,3,order='F') # print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [297]:
arr.reshape(2,3,order='A') # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [299]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [301]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [303]:
arr

array([0, 1, 2, 3, 4, 5])

In [305]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [307]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [309]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [311]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [313]:
arr

array([0, 1, 2, 3, 4, 5])

In [315]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [318]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [320]:
row = 4
col = 5

In [322]:
col

5

In [324]:
row

4

In [326]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [328]:
mat[row,col]

45

In [330]:
mat[4,5]

45

In [332]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [334]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [336]:
col = 6

In [338]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [340]:
mat[6] # default it respresent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [342]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [344]:
# with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [346]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [348]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [350]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [352]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [354]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [356]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [358]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [360]:
row

4

In [362]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [364]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [366]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [368]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [372]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [374]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [376]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [378]:
row

4

In [380]:
col

6

In [382]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [384]:
mat[1,4]

14

In [386]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [390]:
mat[3:-4]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [392]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [394]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [396]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [398]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [400]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [402]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [404]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [406]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [408]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [410]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [412]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [414]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [416]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [418]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [420]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [422]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [424]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [426]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [428]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [430]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [432]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [434]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])