NUMPY Crash Course

In [14]:
import numpy as np

In [16]:
np.__version__

'1.26.4'

In [18]:
np.__version__

'1.26.4'

Creating a list

In [22]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [24]:
type(my_list)

list

below code we are converting list to array

In [29]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
np.arange(20,10)  # first argument should always less than second arguments

array([], dtype=int32)

In [45]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [47]:
np.zeros(3)  # 1D array (parameter tunning)

array([0., 0., 0.])

In [49]:
np.zeros(3,dtype=int)  #1D arry(hyperparameter tunning)

array([0, 0, 0])

In [51]:
np.zeros([2,2]) # 2D array

array([[0., 0.],
       [0., 0.]])

In [53]:
np.zeros([10,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [59]:
np.two(4)

AttributeError: module 'numpy' has no attribute 'two'

In [61]:
np.random.rand(3)

array([0.07889773, 0.24999349, 0.28376006])

In [63]:
np.random.rand(3)

array([0.61156644, 0.54463426, 0.2068352 ])

In [65]:
np.random.rand(3,4)

array([[0.77823536, 0.68515845, 0.94402302, 0.00111701],
       [0.55322682, 0.95146818, 0.04816592, 0.70368975],
       [0.32020299, 0.06028582, 0.28218642, 0.1385327 ]])

In [67]:
np.random.randint(3)

2

In [69]:
np.random.randint(3)

1

In [71]:
np.random.randint(3)

1

In [73]:
np.random.randint(3)

1

In [75]:
np.random.randint(10,20)

19

In [77]:
np.random.randint(10,20)

18

In [79]:
np.random.randint(1,10,4)

array([4, 3, 9, 8])

In [81]:
print(np.random.randint(1,10,4))

[4 6 3 7]


In [83]:
m = np.random.randint(10,40,(10,10))
print(m)

[[13 30 26 33 32 34 29 15 33 10]
 [34 10 28 28 21 33 11 17 35 26]
 [18 25 29 16 18 39 36 12 10 23]
 [37 18 39 16 22 23 35 30 26 30]
 [24 24 38 35 34 26 28 14 10 19]
 [22 25 16 27 23 13 13 11 12 17]
 [21 32 39 30 36 10 23 13 19 31]
 [31 17 19 12 28 36 20 16 12 38]
 [27 28 18 22 35 12 16 28 27 13]
 [27 13 39 35 34 12 31 14 24 24]]


In [85]:
m = np.random.randint(1,10,(4,6))
print(m)

[[8 9 7 5 4 9]
 [8 7 4 9 3 6]
 [2 9 2 2 6 3]
 [4 9 2 3 8 9]]


In [87]:
m[0]

array([8, 9, 7, 5, 4, 9])

array manipulation

In [89]:
m[0] = [4,5,6,7,8,9]
print(m)

[[4 5 6 7 8 9]
 [8 7 4 9 3 6]
 [2 9 2 2 6 3]
 [4 9 2 3 8 9]]


In [92]:
m[2]

array([2, 9, 2, 2, 6, 3])

In [94]:
m[-3]

array([8, 7, 4, 9, 3, 6])

In [96]:
m[-2,-3]

2