Numpy Crash Course

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating Arrays

In [10]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

In [14]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
type(arr)

numpy.ndarray

In [18]:
type(my_list)

list

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(3.0)

array([0., 1., 2.])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [32]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [34]:
np.arange(30,20)

array([], dtype=int32)

In [36]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [38]:
np.arange(10,10)

array([], dtype=int32)

In [40]:
np.arange(10,30,5) 

array([10, 15, 20, 25])

In [42]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [44]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [46]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [48]:
np.zeros(5, dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [50]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [58]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [60]:
zero = np.zeros([2,2])
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [62]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [66]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.zeros((10,30), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [70]:
np.zeros((5,10)) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
print(np.zeros(n,dtype=int)) #hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [76]:
n

(6, 7)

In [78]:
n1 

(6, 8)

In [80]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [82]:
np.ones(3)

array([1., 1., 1.])

In [84]:
np.ones(4,dtype=int)  # hyper parameter tunning

array([1, 1, 1, 1])

In [86]:
np.ones(4)

array([1., 1., 1., 1.])

In [88]:
n

(6, 7)

In [90]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [92]:
np.ones([5,4],dtype=int)  # hyperparameter tunning

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [94]:
np.twos([2,3])

AttributeError: module 'numpy' has no attribute 'twos'

In [96]:
np.ones(2)

array([1., 1.])

In [98]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
np.ones([6,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [102]:
range(5)

range(0, 5)

In [104]:
r = range(5)
r

range(0, 5)

In [106]:
for i in r:
    print(i)

0
1
2
3
4


In [108]:
list(range(5))

[0, 1, 2, 3, 4]

In [110]:
range(1,10)

range(1, 10)

In [112]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [114]:
list(range(1,10,3))

[1, 4, 7]

In [116]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [118]:
rand(3,2)

NameError: name 'rand' is not defined

In [120]:
np.random.rand(5)

array([0.10459281, 0.19744215, 0.70254641, 0.31435973, 0.83813822])

In [122]:
np.random.rand(2,4)

array([[0.28172746, 0.68681081, 0.44666254, 0.13951376],
       [0.09318298, 0.43451385, 0.94963745, 0.98494976]])

In [124]:
np.random.randint(2,4)

2

In [126]:
np.random.randint(2,4)

3

In [128]:
np.random.randint(2,4)

3

In [130]:
np.random.randint(2,20) # 2nd arguments is exclusive

16

In [132]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [134]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [136]:
np.random.randint(0,1)

0

In [138]:
np.random.randint(10,20,5)

array([18, 16, 16, 14, 18])

In [140]:
np.random.randint(1,6,4)

array([5, 2, 5, 1])

In [142]:
np.random.rand(1,6,4)

array([[[0.64709454, 0.85487784, 0.03284531, 0.14872307],
        [0.02264471, 0.06753342, 0.21113092, 0.85217747],
        [0.67519989, 0.24756069, 0.45298147, 0.41298199],
        [0.92929133, 0.47402424, 0.58975208, 0.68856274],
        [0.1106191 , 0.59331108, 0.24695275, 0.5361937 ],
        [0.42431959, 0.64988903, 0.40980498, 0.47405626]]])

In [146]:
np.random.rand(3)

array([0.87397814, 0.3703896 , 0.81828764])

In [148]:
np.random.randint(1)

0

In [150]:
np.random.randint(30,20,10)

ValueError: low >= high

In [152]:
np.random.randint(-30,20,10)

array([-28, -25,  13,  -6,   4,  -2,   7,   9,   8, -28])

In [154]:
np.random.randint(20,30,10)

array([20, 24, 21, 27, 25, 21, 29, 20, 24, 20])

In [156]:
np.random.randint(5,9) 

6

In [160]:
np.random.randint(1,12,10)

array([ 9,  8,  1,  6,  2,  5,  3, 11,  7, 10])

In [162]:
np.random.randint(10,40,[10,10])

array([[21, 12, 21, 16, 28, 10, 35, 39, 33, 15],
       [37, 22, 20, 25, 20, 22, 38, 25, 13, 24],
       [38, 34, 15, 13, 11, 32, 29, 39, 24, 13],
       [14, 27, 10, 13, 17, 21, 24, 29, 38, 37],
       [26, 36, 15, 37, 22, 25, 21, 34, 35, 13],
       [14, 23, 24, 39, 23, 19, 22, 27, 26, 23],
       [27, 16, 19, 25, 11, 26, 26, 34, 32, 15],
       [28, 39, 23, 39, 18, 24, 34, 24, 12, 17],
       [31, 38, 22, 12, 18, 34, 29, 36, 34, 10],
       [23, 27, 27, 25, 32, 13, 19, 33, 18, 38]])

In [164]:
np.random.randint(1,100,[12,12]) 

array([[51, 40, 32, 89, 86, 32, 92, 17, 45,  8,  5, 87],
       [13, 70, 90, 70, 26, 57,  4, 45, 69,  3, 78, 51],
       [54, 69, 11, 45,  4, 63, 75, 58, 39, 57, 70,  4],
       [22, 29, 74, 43, 17, 62, 87, 66,  5, 38, 64, 88],
       [45, 62, 49, 79, 12, 88, 15, 70, 55, 18, 29, 13],
       [81, 88,  6, 55, 22, 27, 30, 77, 44, 58, 95, 55],
       [ 9,  8, 77, 92, 95, 22, 70, 55, 46, 69, 62, 36],
       [64, 36, 27, 20,  8, 47, 57, 43, 20, 60, 97, 86],
       [ 8, 73, 55, 61, 47, 14, 17, 26, 35, 92, 16, 33],
       [99, 15, 48, 74, 34, 24, 97,  2, 61, 64, 38, 81],
       [18, 26, 52,  9, 89, 58, 79, 69, 55, 36, 79, 90],
       [46, 65, 86, 65, 74, 20, 77, 97, 99, 71, 24, 21]])

In [166]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [168]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [170]:
b = np.random.randint(10,20,[5,4])
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [172]:
type(b)

numpy.ndarray

In [174]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [176]:
b[:]

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [178]:
b[1:3]

array([[13, 14, 17, 16],
       [12, 14, 11, 16]])

In [180]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [182]:
b[1,2]

17

In [184]:
b[1,3]

16

In [186]:
b[1,-1]

16

In [188]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [190]:
b[2:3]

array([[12, 14, 11, 16]])

In [192]:
b[0:-2]

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16]])

In [194]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [196]:
b[0,2]

10

In [198]:
b[-5,-3]

12

In [200]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [202]:
b[-4,2]

17

In [204]:
np.random.randint(10,20,(4,4))

array([[14, 18, 15, 17],
       [16, 11, 13, 18],
       [16, 18, 17, 18],
       [15, 10, 15, 13]])

In [206]:
b

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

In [208]:
b[-4,-2]

17

In [210]:
b[-4:2]

array([[13, 14, 17, 16]])

In [212]:
b[:]

array([[19, 12, 10, 14],
       [13, 14, 17, 16],
       [12, 14, 11, 16],
       [17, 13, 17, 11],
       [18, 16, 14, 18]])

Operations

In [217]:
a = np.random.randint(10,20,10)
a

array([15, 11, 14, 12, 11, 18, 10, 14, 10, 19])

In [219]:
id(a)

2140235826544

In [221]:
arr

array([0, 1, 2, 3, 4, 5])

In [223]:
arr2 = np.random.randint(0,100,[10,10])

In [225]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [227]:
arr

array([0, 1, 2, 3, 4, 5])

In [229]:
arr[:4]

array([0, 1, 2, 3])

In [231]:
arr2[:]

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [233]:
arr2[0:5]

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20]])

In [235]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [237]:
arr2[1,4]

87

In [241]:
arr2[-5,5]

39

In [243]:
arr2[-5,-5]

39

In [246]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [248]:
arr2[-1,-2]

6

In [253]:
arr2[::-1] 

array([[33, 46, 35, 36, 79, 11, 91, 53,  6,  9],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [14,  7, 23, 97, 29, 42, 49, 14, 11, 79]])

In [255]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [257]:
arr2[::-2]

array([[33, 46, 35, 36, 79, 11, 91, 53,  6,  9],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66]])

In [259]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [261]:
arr2[::-3]

array([[33, 46, 35, 36, 79, 11, 91, 53,  6,  9],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [14,  7, 23, 97, 29, 42, 49, 14, 11, 79]])

In [263]:
arr2

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66],
       [68, 65, 45, 26, 40, 82, 71, 29, 59,  0],
       [57,  7, 48, 71, 35, 38, 33, 84, 72, 47],
       [33, 46, 35, 36, 79, 11, 91, 53,  6,  9]])

In [265]:
arr2[:-3]

array([[14,  7, 23, 97, 29, 42, 49, 14, 11, 79],
       [58, 47, 71, 75, 87, 48, 51, 85, 72, 66],
       [47, 58, 23,  8, 25, 77, 99, 23, 86, 32],
       [12, 52, 94, 16, 96, 61,  4, 25, 27, 52],
       [ 2, 38, 75, 72,  7, 28, 94,  6, 49, 20],
       [84, 70, 94, 98, 92, 39, 92, 93, 99, 81],
       [80, 79, 81, 69, 98,  9, 25, 50, 42, 66]])

In [267]:
arr

array([0, 1, 2, 3, 4, 5])

In [269]:
arr.max()

5

In [271]:
arr.min()

0

In [273]:
arr

array([0, 1, 2, 3, 4, 5])

In [275]:
arr.mean()

2.5

In [277]:
arr

array([0, 1, 2, 3, 4, 5])

In [279]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [283]:
from numpy import * 
a = array([1, 2, 3, 4, 9])
median(a)

3.0

without work on import can you find the median ,mode

In [286]:
arr

array([0, 1, 2, 3, 4, 5])

In [288]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [290]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [292]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [294]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [296]:
arr

array([0, 1, 2, 3, 4, 5])

In [298]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [300]:
arr.reshape(2,3,order='F') # print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [302]:
arr.reshape(2,3,order='A') # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [304]:
arr

array([0, 1, 2, 3, 4, 5])

In [306]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [308]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [310]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [312]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [314]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [316]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [318]:
arr

array([0, 1, 2, 3, 4, 5])

In [320]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [323]:
mat = np.arange(0,100).reshape(10,10)

In [325]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [327]:
row = 4
col = 5

In [329]:
mat[row,col]

45

In [331]:
mat[4,5]

45

In [333]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [335]:
col = 6

In [337]:
mat[6] 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [339]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [341]:
# with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [343]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [345]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [347]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [349]:
mat[7,:]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [351]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [353]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [355]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [357]:
row

4

In [359]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [361]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [363]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [365]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [367]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [369]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [371]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [373]:
row

4

In [375]:
col

6

In [377]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [379]:
mat[1,4]

14

In [381]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [383]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [385]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [387]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [389]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [391]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [393]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [395]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [397]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [399]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [401]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [403]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [405]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [407]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [409]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [411]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [413]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [415]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [417]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [419]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [421]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [423]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [425]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [427]:
mat[::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [429]:
mat[2:6,2:4] # 2:6 --> represent row part /// 1:3 --> it indicates only column parts
             # 22,23 to 52,53

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [431]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [433]:
mat[0,1]

1

In [435]:
mat[1,6]

16

In [437]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [439]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [441]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [443]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [445]:
mat[1:2,2:4]

array([[12, 13]])

In [447]:
mat[2:3,2:3]

array([[22]])

In [449]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [451]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [453]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [455]:
mat[2:3,4:5]

array([[24]])

Masking

In [459]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [461]:
id(mat)

2140244325648

In [463]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [465]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [469]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [471]:
mat[mat==50]

array([50])

In [473]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [475]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [477]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [479]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [481]:
a4 = mat[mat == 50]

In [483]:
a4

array([50])