In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(a[0])

[1 2 3 4]


In [10]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [12]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,1),dtype=int)

array([[0],
       [0],
       [0]])

In [28]:
np.ones(2)

array([1., 1.])

In [31]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [33]:
# create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [35]:
# And enve an array that contains a range of evenly spaced intervals. To do this, you will
#specify the first number, last  number and the step size
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [37]:
# You can also use np.linspace() to create an array with values that are spaced linearly in a 
# specified interval:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
# while the default data type is floating point(np.float64), you can explictly specify 
# which data type you want using the dtype keyword.
x = np.ones(2, dtype=int)
x

array([1, 1])

Adding, removing and sorting elements

In [46]:
# Sorting an elements is simple with np.sort().
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [48]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [52]:
# Concatenate 
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

In [60]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array?

In [63]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [65]:
# To find the numer of dimensions of the array,run:
array_example.ndim

3

In [67]:
# To find the total number of elements in the array, run:
array_example.size

24

In [71]:
# And to find the shape of you array, run:
array_example.shape

(3, 2, 4)

Can You reshape an array?

In [74]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [76]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [80]:
# with np.reshape, you can specify a few option parameters:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (How to add a new axis to an array)

In [85]:
# You can use np.newaxis and np.expand_dims to increase the dimensions of yours existing array.
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [87]:
# you can use np.newaxis to add a new axis:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [89]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [91]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [95]:
# you can also expand an array by inserting a new axis at a specified position with np.expand_dims
a = np.array([1,2,3, 4, 5,6])
a.shape

(6,)

In [97]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [99]:
# you can add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indxing and Slicing

In [102]:
data = np.array([1,2,3])
data[1]

2

In [104]:
data[0:2]

array([1, 2])

In [106]:
data[1:]

array([2, 3])

In [108]:
data[-2:]

array([2, 3])

In [110]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
a.shape

(3, 4)

In [114]:
a.size

12

In [116]:
a.ndim

2

In [118]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
print(a[a < 5])

[1 2 3 4]


In [122]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [124]:
# you can select elements that are divisible by 2
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [126]:
# you can select elements that satisfy two conditions using the & and | operators:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [128]:
# you can also use of the logical operators & and | in order to return boolean values 
five_up = (a < 5) | (a == 5)
print(five_up)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [134]:
# You  can use np.zeros() to select elements or indices from an array.
a = np.array([[1, 2, 3, 4], [5, 6, 7 ,8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [138]:
list_of_coordinates = list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [140]:
not_there = np.nonzero( a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


How to create an array from existing data

In [143]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [147]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [149]:
# you can stack two existing arrays, both vertically and horizontally.
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [153]:
print(a1,'\n')
print(a2)

[[1 1]
 [2 2]] 

[[3 3]
 [4 4]]


In [155]:
# you can stack vertically with vstack:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [157]:
# stack them horizonatally with hstack:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [161]:
# you can split an array into several smaller arrays using hsplit.
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [163]:
# if you want to split this array into three equally shaped arrays, you would run:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [165]:
# if you want to split your array after the third and fourth column,you'd run:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [169]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
# Now we create an array b1 by slicing a and modify the first element of b1. This will modify
# the corresponding element in a as well
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [175]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [177]:
a 

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
# using the copy method will make a complete copy of the array and its data(a deep copy)
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations

In [186]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data,'\n',ones)
data + ones

[1 2] 
 [1 1]


array([2, 3])

In [188]:
data - ones

array([0, 1])

In [197]:
data / data

array([1., 1.])

In [199]:
# if you want to find the sum of the elements in an array, you'd use sum().THis works for 1D arrays, 2D arrays and arrays in higher dimensions
a= np.array([1, 2, 3, 4])
a.sum()

10

In [205]:
# To add the rows or the columns in a 2D array, you will spedify the axis
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [203]:
# you can sum over the axis of rows with:
b.sum(axis=0)

array([3, 3])

In [207]:
# you can sum over the axis of columns with:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [210]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [212]:
data.max()

2.0

In [214]:
data.min()

1.0

In [216]:
data.sum()

3.0

In [218]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [220]:
a.sum()

4.8595784

In [222]:
a.min()

0.05093587

In [224]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

Creating matrices

In [229]:
# you can pass python lists to create a 2-D array (or "matrix") to represent them in Numpy
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [231]:
# indexing and slicing operations are useful when you're manipulation matrices:
data[0,1]

2

In [233]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [235]:
data[0:2, 0]

array([1, 3])

In [237]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [239]:
data.max()

6

In [241]:
data.min()

1

In [243]:
data.sum()

21

In [245]:
data = np.array([[1,2], [5,3], [4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [247]:
data.max(axis=0)

array([5, 6])

In [249]:
data.max(axis=1)

array([2, 5, 6])

In [251]:
# Once you've creted your matrices, you can add and multiply them using arithmetic operators if
# you have two matrices that are the same size.

data = np.array([[1,2], [3,4]])
ones = np.array([[1,1], [1,1]])
data + ones

array([[2, 3],
       [4, 5]])

In [253]:
# you can do these arithmetic operations on matrices of different sizes, but only if matrix has
# only one column or one row. In case, Numpy will use its broadcast rules for the operation.

data = np.array([[1,2], [3,4], [5,6]])
ones_row = np.array([[1,1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [255]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [257]:
np.ones(3)

array([1., 1., 1.])

In [259]:
np.zeros(3)

array([0., 0., 0.])

In [263]:
rng = np.random.default_rng()
rng.random(3)

array([0.0884999 , 0.91274388, 0.20252949])

In [265]:
# You can also use ones(), zeros(),and random() to create a 2D array if you give them a tuple describing the dimensions of the matrix:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [267]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [279]:
np.random.rand(3,2)

array([[0.08485236, 0.41156711],
       [0.98716696, 0.90890571],
       [0.1484094 , 0.02644757]])

How to get unique items and counts

In [282]:
a = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [286]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [288]:
# you can pass the return_counts argument in np.unique() along with you array to get the frequency count of unique values in a Numpy array
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[2 2 2 2 1 1 1 1 1 1]


In [290]:
a_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [1,2,3,4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [292]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [296]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [298]:
unique_cols = np.unique(a_2d, axis=1)
print(unique_cols)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


Transposing and reshaping a matrix

In [303]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [305]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [307]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [309]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [311]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [313]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

How to reverse an array

Reversing a 1D array

In [319]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [323]:
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

Reversing a 2D array

In [326]:
arr_2d = np.array([[1,2,3,4], [5, 6, 7, 8], [9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [328]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [332]:
# you can reverse the content in all of the rows and all columns with:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [334]:
# you can easily reverse only the rows with:
reversed_arr_rows = np.flip(arr_2d, axis = 0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [338]:
# revesed only the columns with:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [340]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [342]:
# you can also reverse the contents of only one column or row
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [344]:
# you can also reverse the column at index position 1
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [347]:
# There are two ways to flatten an array: .flatten() and .ravel(). The primary difference b/w 
# the two is that the new array created using ravel() is actually a reference to the parent array
# This means tha any changes to the new array will affect the parent array as well. since ravel doesn't create copy , so it is memory efficient

x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [349]:
# when use flatten ,changes to you new array won't change the parent array.
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [351]:
a1 = x.flatten()
a1[0] = 99
print(x,'\n')  # Original array
print(a1) # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[99  2  3  4  5  6  7  8  9 10 11 12]


In [353]:
# But when you use ravel, the change you make to the new array will affect the parent array.

a2 = x.ravel()
a2[0] = 98
print(x,'\n') # Original array
print(a2) # New array


[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[98  2  3  4  5  6  7  8  9 10 11 12]
