Array Creation Functions

In [3]:
import numpy as np

Create an array from a list

In [7]:
a = np.array([1,2,3])
print('Array a:', a)

Array a: [1 2 3]


In [9]:
# create an array with evenly spaced values
b = np.arange(0,10,3) # values from 0 to 10 with step 3
print("Array b:",b)

Array b: [0 3 6 9]


In [11]:
# create an array filled with zeros
d = np.zeros((2,3)) # 2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# create an array filled with zeros
d = np.zeros((2,3),dtype=int) # 2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [17]:
# create an array filled with ones
e = np.ones((3,2)) # 3x2 array of ones
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


Create an  Identity matrix

In [23]:
f = np.eye(4) # 4x4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Array Manipulation Functions

In [28]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) # Reshape to 1x3
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [30]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(f1,'\n')
flattened = np.ravel(f1) # Flatten to 1D array
print("Flatttened array:\n", flattened)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

Flatttened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [32]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [36]:
# stack array vertically 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2, b2]) # stack a and b vertically
print("stacked arrays:\n",stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [38]:
# stack array horizontal
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]


3. Mathemetical Functions

In [41]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2) # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [45]:
# square each element
squared = np.power(g,2) # square each element
print("Squared g:\n",squared)

Squared g:
 [ 1  4  9 16]


In [47]:
# Square root of each element
sqrt_val = np.sqrt(g) # square root of each element
print("Square root of g:\n", sqrt_val)

Square root of g:
 [1.         1.41421356 1.73205081 2.        ]


In [49]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [51]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) # Dot product of a and g
print("Dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [53]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [57]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) 
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


Statistical Functions

In [64]:
# Mean of an array
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [66]:
# standard deviation of an array
var = np.var(s)
print("variance of s:", var)

variance of s: 1.25


In [70]:
# standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [73]:
s

array([1, 2, 3, 4])

In [75]:
# standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [79]:
s

array([1, 2, 3, 4])

In [81]:
# minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [83]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


6. Random Sampling Functions

In [86]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random Values:", random_vals)

Random Values: [0.71407147 0.78454555 0.16206779]


In [88]:
#set seed for reproducibility
np.random.seed(0)

In [90]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [92]:
random_vals

array([0.5488135 , 0.71518937, 0.60276338])

In [110]:
# Generate random integers
rand_ints = np.random.randint(0,10,size=5) # Random integer between 0 and 10
print("Random integers:",rand_ints)

Random integers: [7 6 8 8 1]


In [115]:
# set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0,10,size=5) # Random integers between 0 and 10)
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


In [117]:
print(rand_ints)

[5 0 3 3 7]


7. Boolean & Logical Functions

In [124]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) # check if all are True
print("Is All elements True:",all_true)

Is All elements True: False


In [126]:
# check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test) # check if all are True
print("All elements True:", all_true) 

All elements True: False


In [128]:
#check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.all(logical_test) # check if all are true
print("All elements True:", all_true)

All elements True: False


In [130]:
# Check if any elements are True

# any
any_true = np.any(logical_test) # check if any are true
print("Any elements True:", any_true)

Any elements True: True


8. Set Operations

In [135]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersections of a and b:", intersection)

Intersections of a and b: [3 4]


In [137]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


9. Array Attribute Functions

In [140]:
# Array attributes
a = np.array([1,2,3])
shape = a.shape # shape of the array
size = a.size # Number of elements
dimensions = a.ndim # Number of dimension
dtype = a.dtype # Data type of the array

print("Shape of a:", shape)
print("Size of a :",size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a : 3
Number of dimensions of a: 1
Data type of a: int32


10. Other Functions

In [143]:
# create a copy of an array
a = np.array([1,2,3])
copied_array = np.copy(a) # create a copy of array a 
print("copied array:",copied_array)

copied array: [1 2 3]


In [145]:
# size in bytes of an array
array_size_in_bytes = a.nbytes # size in bytes
print("size of a in bytes:",array_size_in_bytes)

size of a in bytes: 12


In [147]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array) # check if array share memory
print("Do a and copied_array share memory?",shared)

Do a and copied_array share memory? False
